## 1. Build stage
FROM adoptopenjdk/opendjk17:ubi as build

## Create app directory
WORKDIR /app


## Copy the project files
COPY mvnw .
COPY .mvn .mvn

## Copy the pom.xml file
COPY pom.xml .

## Build all dependencies
## This is a separate step so the dependencies
## will be cached
RUN ./mvnw dependency:go-offline -B

## Copy the project files
COPY src src

## Package the application and its dependencies
RUN ./mvnw package -DskipTests
RUN mkdir -p target/dependency && (cd target/dependency; jar -xf ../*.jar)

## 2. Run stage
FROM adoptopenjdk/opendjk17:ubi

ARG DEPENDENCY=/app/target/dependency

## Copy project dependencies from the build stage
COPY --from=build ${DEPENDENCY}/BOOT-INF/lib /app/lib
COPY --from=build ${DEPENDENCY}/META-INF /app/META-INF
COPY --from=build ${DEPENDENCY}/BOOT-INF/classes /app

## Run the Spring boot application
ENTRYPOINT ["java","-cp","app:app/lib/*","com.dientsys.dientsys.DientsysApplication"]




